name: Deploy

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Desplegar
      run: python deploy.py
      if: success()
